#!/usr/bin/env bash

mkdir -p out/
rm -rf out/*

textql -header -output-header -sql "

WITH builds AS (
  SELECT
    date(substr(created_at, 1, 19), 'weekday 0', '-7 days') as week_of,
    summary_status
  FROM session
  WHERE
    summary_status='passed' OR
    summary_status='failed'
),

builds_per_week AS (
  SELECT
    week_of,
    COUNT(*) as total_num_builds
  FROM builds
  GROUP BY week_of
)

SELECT
  builds.week_of as week_of,
  builds.summary_status as status,
  COUNT(*) as num_passing,
  builds_per_week.total_num_builds as total_num_builds,
  printf(\"%.2f\", COUNT(*)*1.0/builds_per_week.total_num_builds * 100) as percentage
FROM builds
LEFT JOIN builds_per_week ON builds_per_week.week_of = builds.week_of
WHERE
  builds.summary_status = 'passed'

GROUP BY builds.week_of, builds.summary_status
ORDER BY builds.week_of ASC
;" $1 > out/result.csv

gnuplot plot.plt
